# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KKn8LZeFQJ95bVUnXMLb2rIK-pa2io9I
"""

import sys
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Read each CSV file into a DataFrame

df1 = pd.read_csv('/content/drive/MyDrive/Actuary/Project- Reserving/comauto_pos.csv')
df2 = pd.read_csv('/content/drive/MyDrive/Actuary/Project- Reserving/medmal_pos.csv')
df3 = pd.read_csv('/content/drive/MyDrive/Actuary/Project- Reserving/othliab_pos.csv')
df4 = pd.read_csv('/content/drive/MyDrive/Actuary/Project- Reserving/ppauto_pos.csv')
df5 = pd.read_csv('/content/drive/MyDrive/Actuary/Project- Reserving/prodliab_pos.csv')
df6 = pd.read_csv('/content/drive/MyDrive/Actuary/Project- Reserving/wkcomp_pos.csv')
### these are the files downloaded directly from https://www.casact.org/publications-research/research/research-resources/loss-reserving-data-pulled-naic-schedule-p

# Add a new column indicating the line of business
df1['Line_of_Business'] = 'LOB1'  #LOB1->commercial auto
df2['Line_of_Business'] = 'LOB2'  #LOB2->medical malpractice
df3['Line_of_Business'] = 'LOB3'  #LOB3->other liabilities
df4['Line_of_Business'] = 'LOB4'  #LOB4->private passenger auto
df5['Line_of_Business'] = 'LOB5'  #LOB5->product liability
df6['Line_of_Business'] = 'LOB6'  #LOB6->worker's compensation

# Concatenate all DataFrames into one
merged_df = pd.concat([df1, df2, df3, df4, df5, df6], ignore_index=True)

# Encode the categorical column using one-hot encoding
encoded_df = pd.get_dummies(merged_df, columns=['Line_of_Business'])

# Alternatively, you can use label encoding if you prefer:
# from sklearn.preprocessing import LabelEncoder
# label_encoder = LabelEncoder()
# encoded_df['Line_of_Business'] = label_encoder.fit_transform(encoded_df['Line_of_Business'])

# Save the merged and encoded DataFrame to a new CSV file
encoded_df.to_csv('/content/drive/MyDrive/Actuary/Project- Reserving/merged_data.csv', index=False)

df = pd.read_csv('/content/drive/MyDrive/Actuary/Project- Reserving/merged_data.csv')
num_rows, num_columns = df.shape
df.shape

# I want to create incremental paid claims column

num_rows, num_columns = df.shape
df['IncPaid']=0
j = 6  # column index of cum paid loss
for i in range(0, num_rows - 10+2, 10):
    df.iloc[i,19]=df.iloc[i,j]
    i+=1
    for k in range(9):
        df.iloc[i , 19] = df.iloc[i , j] - df.iloc[i -1, j]
        #print("current",df.iloc[i , j],"previous", df.iloc[i -1, 19]," i:",i," j:",j , "curdata: ", df.iloc[i , j],"Updata:",df.iloc[i , j] - df.iloc[i -1, 19])
        i=i+1
df.to_csv('/content/drive/MyDrive/Actuary/Project- Reserving/merged_data.csv', index=False)